### ISSUE TITLE
Constrain Middlewares to only be executed for certain routes.

### ISSUE THREAD

**Issue by Brammm** [mindplay-dk/middleman#12]
An often seen feature in frameworks that implement middlewares is the option to constrain middlewares from only being executed for certain routes (e.g. an AuthenticationMiddleware that's only executed for `/admin` routes). 

Is this something that you'd wish to support with this library?

**Comment by mindplay-dk** [comment]
I can't give you a complete answer right now, but, generally, no.

When you take something like authentication for `/admin` paths and implement it as separate middleware from the actual `/admin` actions, what you get is not really modularity, but fragmentation. There's dependency (and likely coupling) between those components - you can hide it, but it's still there; that is, your application doesn't work correctly unless both components are correctly configured, e.g. your admin actions would not require authentication, which may (or may not) even make sense, depending on your application, but most applications do need to know the User ID, so this separation doesn't really make sense.

I'm addressing your specific use-case example, but this is generally the case - if you need to filter requests e.g. by path, that's probably something that can and should be done with middleware; other than sheer convenience, there's no practical reason why the dispatcher should implement middleware for you - we tend to favor simplicity over ease of use.

You're most likely trying to use middleware as your application framework, which is tempting, but ultimately not a good idea - authentication is a domain concern, and should be handled in the domain along with the rest of your domain concerns.

I realize this opinion may seem a bit "controversial", given that most other frameworks would probably provide this feature, but our team has not needed this feature, because we use middleware as a low-level framework for the HTTP front-controller strictly; anything domain-related stays in the domain. We view middleware as a framework to abstract the HTTP request/response cycle, not as an application framework.

I'm sure a much longer reply is necessary to explain that philosophy.

**Comment by Brammm** [comment]
Thanks for the reply, there's some very interesting insights!
